# Generated by Django 3.1 on 2020-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200829_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='orderid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
