# Generated by Django 3.1 on 2020-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.ManyToManyField(blank=True, null=True, to='store.Statuscheck'),
        ),
    ]
