# Generated by Django 3.1 on 2020-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
