# Generated by Django 3.1 on 2020-09-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200903_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderstatus',
        ),
    ]
