# Generated by Django 3.1 on 2020-09-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
