# Generated by Django 3.1 on 2020-09-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200905_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderstatus',
            new_name='order_completed',
        ),
    ]
