# Generated by Django 3.1 on 2020-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200911_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='small'),
            preserve_default=False,
        ),
    ]
