# Generated by Django 3.1 on 2020-09-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
