# Generated by Django 3.1 on 2020-09-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_status',
            field=models.CharField(default='added', max_length=5000),
        ),
    ]
